// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPqfBvfBrZVcPbJaE2xZn7shAb3_Cg66E',
    appId: '1:726615209345:web:a56d3e8c944ed9f1b82480',
    messagingSenderId: '726615209345',
    projectId: 'kawaii-passion-hub-orders',
    authDomain: 'kawaii-passion-hub-orders.firebaseapp.com',
    databaseURL: 'https://kawaii-passion-hub-orders-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kawaii-passion-hub-orders.appspot.com',
    measurementId: 'G-J56CN683V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuBIPk95d4QPaxbyd7DHXPzwhmwOp37_U',
    appId: '1:726615209345:android:1c5ce0040f04032eb82480',
    messagingSenderId: '726615209345',
    projectId: 'kawaii-passion-hub-orders',
    databaseURL: 'https://kawaii-passion-hub-orders-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kawaii-passion-hub-orders.appspot.com',
  );
}
